# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  iopad-benchmarks:
    dependencies:
    - base
    - iopad
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: iopad is a new Haskeleton package.
executables:
  iopad:
    dependencies:
    - base
    - iopad
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/iopad
library:
  dependencies:
  - base
  - bytestring
  - time
  - mtl
  - containers
  - data-default
  source-dirs: library
license: MIT
maintainer: Author name here
name: iopad
synopsis: A new Haskeleton package.
tests:
  iopad-test-suite:
    dependencies:
    - base
    - iopad
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
