benchmarks:
  iopad-benchmarks:
    dependencies:
    - base
    - iopad
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: Touchpad gestures as an alternative to the keyboard
executables:
  iopad:
    dependencies:
    - base
    - iopad
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/iopad
library:
  dependencies:
  - base
  - bytestring
  - time
  - mtl
  - containers
  - data-default
  source-dirs: library
maintainer: BlackCap
name: iopad
synopsis: Touchpad gestures as an alternative to the keyboard
version: '0.0.0'
